services:
  - type: web
    name: mpesa-backend
    env: python
    region: frankfurt
    rootDir: backend
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: SECRET_KEY
        sync: false
      - key: FERNET_KEY
        sync: false
      - key: METABASE_SECRET_KEY
        sync: false
      - key: METABASE_SITE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: DATABASE_URL
        sync: false
